### ISSUE TITLE
Learning Ionic Fundamentals

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#2]
Related to user story #13
Deadline: July 16, 2022

Assigned Person: Benson Atencio
Progress: 100%

**Comment by Gabriel19-00477** [comment]
Benson, you may provide a picture or proof pertaining of your completion in learning ionic fundamentals. A screenshot of your screen will do. Thank you!

**Comment by BensonAtencio** [comment]
![Screenshot 2022-07-15 122319](https://user-images.githubusercontent.com/108327522/179150278-5d59aa1f-647b-4312-9e90-6458c49b4f3d.jpg)

**Comment by BensonAtencio** [comment]
![Screenshot 2022-07-15 121846](https://user-images.githubusercontent.com/108327522/179150403-8b54dfc0-cf43-4bed-aae7-361bbdab8087.jpg)
![Screenshot 2022-07-15 122428](https://user-images.githubusercontent.com/108327522/179150410-63ecc79c-ab35-408e-b8f7-d6469438f8ad.jpg)

I have also tried creating a simple login page that uses firebase for authentication.

**Comment by BensonAtencio** [comment]
It is all based from the video tutorial posted by sir JM

**Comment by BensonAtencio** [comment]
[https://ionicframework.com/docs/components](url)

this is the link of the ionic documentation if you want to try creating some projects with buttons and a lot of different ionic components

**Comment by Gabriel19-00477** [comment]
Thank you, Benson. Your updates were appreciated!
