### ISSUE TITLE
Create a LogIn and Register Authentication and connection to the firebase database of Lazatech Educate

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#20]
Assigned Person: Benson

Progress: 100%

**Comment by BensonAtencio** [comment]
These are some of the proofs from the code

![Screenshot 2022-07-26 211338](https://user-images.githubusercontent.com/108327522/181015210-9922f0a6-52ee-43c9-8827-7ac9f1b23e43.jpg)
![Screenshot 2022-07-26 211404](https://user-images.githubusercontent.com/108327522/181015232-795fdd76-9c47-44e2-8362-0dd75e01328c.jpg)
![Screenshot 2022-07-26 211505](https://user-images.githubusercontent.com/108327522/181015251-cd260e2a-11d8-4bf2-9ded-6c499c5e3f25.jpg)
 
These are from firebase
![Screenshot 2022-07-26 211546](https://user-images.githubusercontent.com/108327522/181015561-a66bba8d-7baa-4164-8c28-a31f208d6982.jpg)
![Screenshot 2022-07-26 211620](https://user-images.githubusercontent.com/108327522/181015584-2a3b12fc-a771-4791-aae0-e2c6258b47bb.jpg)

**Comment by BensonAtencio** [comment]
I have also added a logout function
![Screenshot 2022-07-26 212122](https://user-images.githubusercontent.com/108327522/181016060-d7cf779c-3494-48ca-ab4a-4380cc790d0f.jpg)

**Comment by Gabriel19-00477** [comment]
That's noted. Rest assured that all of the functions will be visible on the system design diagrams.
