### ISSUE TITLE
Create merch designs for "Store" page

### ISSUE THREAD

**Issue by coleenjill-sajo** [Gabriel19-00477/Lazatech-Educate#21]
Progress: 80%
Assigned Person: Coleen Jill Sajo

Canva Link: https://www.canva.com/design/DAFHm-U61fo/PgWMH9__nP-MdybR9fX3hw/view?utm_content=DAFHm-U61fo&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by coleenjill-sajo** [comment]
Progress updated from 0% to 40%

- Decided to settle on four items: a mug, a t-shirt, a tumbler, and a glass
- Decide to make two versions for each item

![image](https://user-images.githubusercontent.com/108327605/181249716-24e0a81c-1e53-44d5-8bdb-37d60b488a78.png)

**Comment by coleenjill-sajo** [comment]
Progress updated from 40% to 80%

- Items have now been: a mug, a t-shirt, a tumbler, and a tote bag.
- Approval of designs needed from @Gabriel19-00477 

![image](https://user-images.githubusercontent.com/108327605/181252850-b5b1475d-6860-46c2-84d1-858f0e523cd3.png)

**Comment by Gabriel19-00477** [comment]
What a nice designs for our merchandize. Thank you for your effort!
