### ISSUE TITLE
Construct Firebase database connection for the Login and sign up

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#24]

**Comment by BensonAtencio** [comment]
These are some snippets of the code from the login, register or signup typescript files

I have also created a service that can be used in login and logout

![Screenshot 2022-07-27 214422](https://user-images.githubusercontent.com/108327522/181262589-9e4f4834-4fa3-42cc-9bd7-44f0cc8ca732.jpg)

![Screenshot 2022-07-27 214345](https://user-images.githubusercontent.com/108327522/181262603-ff84cf28-fd52-4811-a791-e2f9e0c6e15f.jpg)

![Screenshot 2022-07-27 214323](https://user-images.githubusercontent.com/108327522/181262629-79a01680-027f-4814-9e9b-e13f59606080.jpg)

I have also included a forgot password functionality
![Screenshot 2022-07-27 214449](https://user-images.githubusercontent.com/108327522/181262661-73a9ed6b-73bf-4bbc-bc72-05ff7ad49af2.jpg)

**Comment by Gabriel19-00477** [comment]
That's a well designed backend script for our project. I've already tested it all and they all works. Thanks!
