### ISSUE TITLE
Construct a script for adding a token to the balance of a user once a question was answered on the quiz.

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#25]

**Comment by BensonAtencio** [comment]
This is the idea I just put it in a function for testing. It is working as it should and the database gets updated with just a click of a button. 

Of course it will be different when we apply it to the quiz but the concept is the same 

![Screenshot 2022-07-28 202924](https://user-images.githubusercontent.com/108327522/181505115-91cc0ed2-54a3-43b3-9961-314392a8f0f6.jpg)
