### ISSUE TITLE
Create Lazatech Educate's Logo

### ISSUE THREAD

**Issue by coleenjill-sajo** [Gabriel19-00477/Lazatech-Educate#26]
Progress: 80%
Assigned Person: Coleen Jill Sajo

Canva Link: https://www.canva.com/design/DAFHtCrJdws/Mko84fx_JmomnPlLi5QeRA/view?utm_content=DAFHtCrJdws&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by coleenjill-sajo** [comment]
Drafting a design.
![image](https://user-images.githubusercontent.com/108327605/181514403-4d9fb2ef-887e-46d1-9f16-7ededb096ace.png)

**Comment by coleenjill-sajo** [comment]
Progress updated from 50% to 80%
- Created five proposed logo designs
- Approval needed from @Gabriel19-00477 
![image](https://user-images.githubusercontent.com/108327605/181514999-5299c88e-afb6-4472-8015-7d3117217c5c.png)

**Comment by Gabriel19-00477** [comment]
What a nice logo designs. Thank you!

**Comment by Gabriel19-00477** [comment]
Final logo for Lazatech Educate:
![Uploading 20220731_113855_0002.png…]()
