### ISSUE TITLE
Construct the Marketplace/store page with the Lazatech Merchadizes

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#27]

**Comment by Gabriel19-00477** [comment]
Thanks. Please be aware that every item, when availed by a user, will subtract their cost from the token balance of that user. 
We'll see how can we implement that logic and script.

**Comment by BensonAtencio** [comment]
I'm now currently working on that part.

**Comment by Gabriel19-00477** [comment]
That's great. Thank's for the update!
