### ISSUE TITLE
Learning Typescript Fundamentals

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#3]
Related to user story #13
Assigned Person: Coleen Jill Sajo

Progress: 100% DONE

- OOP can be further familiarized and practiced upon experimenting and learning Angular & Ionic
- Progress will be based on my progress on W3School's [Exercises for Typescript](https://www.w3schools.com/typescript/exercise.php)

**Comment by coleenjill-sajo** [comment]
Newly assigned task acknowledged.

Will provide updates on progress accordingly.

**Comment by coleenjill-sajo** [comment]
Progress updated from 50% to 60%

**Comment by coleenjill-sajo** [comment]
Progress updated from 60% to 75%

**Comment by Gabriel19-00477** [comment]
Thank you for the update. We'll need to have an evidence of the progress or output. An ss of your screen will do, I think.

**Comment by coleenjill-sajo** [comment]
Progress updated from 75% to 85%.

- Will focus more on learning the fundamentals of Typescript
- Thinking about finishing at least finishing Typescript exercises in W3Schools within the week.
- Will prioritize in learning OOP by next week to maximize time on learning both Angular and Ionic.

![image](https://user-images.githubusercontent.com/108327605/178934281-8cfd6d2e-d08e-4cec-84cd-4ef7fa709ab8.png)
![image](https://user-images.githubusercontent.com/108327605/178934341-16dae5a6-17e4-46c4-9174-aab31515bfa9.png)

**Comment by coleenjill-sajo** [comment]
**Mini-update:**
- Completely forgot that technically speaking, "implements" and "extends" is pretty much used in OOP. ("Inheritance", baby~)
- Decided to experiment using the code from the [Typescript crash course YT video](https://www.youtube.com/watch?v=BCg4U1FzODs&t=887s).
![image](https://user-images.githubusercontent.com/108327605/178939193-d2595cab-d22f-4a16-9482-7c9f06f5c3d8.png)

**Comment by coleenjill-sajo** [comment]
Progress updated from 85% to 100%.

- Was able to finish all the Typescript Exercises in W3Schools.
- Will probably consider to do some bit of more self-learning and practice.

![image](https://user-images.githubusercontent.com/108327605/178943479-2477b59b-2cf6-474e-9584-6d27c78dafdd.png)

**Comment by Gabriel19-00477** [comment]
Thank you very much for the update. Your efforts are greatly appreciated!
