### ISSUE TITLE
Construct the algorithm and script for Lazatech Courses Quiz

### ISSUE THREAD

**Issue by Gabriel19-00477** [Gabriel19-00477/Lazatech-Educate#31]
Assigned Person: Benson and Gab
Progress: 100%

**Comment by BensonAtencio** [comment]
These are the codes from the quiz page html and typescript. I have also included some part of the json file.

![Screenshot 2022-08-01 144847](https://user-images.githubusercontent.com/108327522/182089775-51a33265-cd18-4bd1-8a72-91956a754f68.jpg)
![Screenshot 2022-08-01 144936](https://user-images.githubusercontent.com/108327522/182089794-d1735670-79ff-472b-9768-ecd2a64996c5.jpg)
![Screenshot 2022-08-01 144951](https://user-images.githubusercontent.com/108327522/182089812-c20cb5c3-3411-4543-ad23-c2fd08f184fa.jpg)
![Screenshot 2022-08-01 145016](https://user-images.githubusercontent.com/108327522/182089823-8f1a832d-14d2-4d65-b76e-611b06ad9343.jpg)
![Screenshot 2022-08-01 145043](https://user-images.githubusercontent.com/108327522/182089835-a6008776-7031-42cf-b661-cf4599f21c44.jpg)
![Screenshot 2022-08-01 145117](https://user-images.githubusercontent.com/108327522/182089846-f010bac0-7bc1-44d5-9299-5c63b4c7e8ea.jpg)

These are some pictures from the quiz

![Screenshot 2022-08-01 145610](https://user-images.githubusercontent.com/108327522/182090780-7f7edbcc-39e7-4a56-ad36-e69ffe8f3382.jpg)
![Screenshot 2022-08-01 145746](https://user-images.githubusercontent.com/108327522/182090793-9f43f9b5-1da1-44c8-b2fb-6ffe47489381.jpg)
![Screenshot 2022-08-01 145800](https://user-images.githubusercontent.com/108327522/182090806-34cc313e-0641-435d-bc22-aaf39f899aff.jpg)
![Screenshot 2022-08-01 145816](https://user-images.githubusercontent.com/108327522/182090823-5f67413f-c2a2-4868-98fd-222300763774.jpg)
![Screenshot 2022-08-01 145851](https://user-images.githubusercontent.com/108327522/182090841-b5c73edf-f9ee-47e8-82c8-6bcde0e9a2da.jpg)

**Comment by Gabriel19-00477** [comment]
Thank you for the update!
